name: load-stress-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  load-stress-tests:
    name: Build Docker image and run stress test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k6
        run: |
          curl https://github.com/loadimpact/k6/releases/download/v0.26.2/k6-v0.26.2-linux64.tar.gz -L | tar xvz --strip-components 1
      - name: Install packages
        run: |
          npm install
      - name: Start server and run tests
        run: |
          npm start & npx wait-on http://localhost:8080
          ./k6 run stress-tests/test1.js
